// 全站词典：所有页面共享的导航、按钮、状态、页脚与登录页词条
// 归档纪律（AGENTS.md 硬性约束 2/3）：键 = GitHub 实际渲染的英文原文精确串；
// 仅特定页面出现的词条进 pages/<页名>.ts，高风险泛化短词靠不收录回避

import type { GlobalDict } from "../shared/types.ts";
import { commonRules } from "./rules.ts";

export const globalDict: GlobalDict = {
	entries: {
		// —— 顶部导航与会话 ——
		"Skip to content": "跳到主要内容",
		Homepage: "主页",
		Dashboard: "仪表板",
		"Pull requests": "拉取请求",
		Issues: "议题",
		Codespaces: "代码空间",
		Marketplace: "市场",
		Explore: "探索",
		Sponsors: "赞助",
		"Sign in": "登录",
		"Sign up": "注册",
		"Sign out": "退出登录",
		Notifications: "通知",
		Settings: "设置",
		"Feature preview": "功能预览",
		Help: "帮助",
		"Search or jump to…": "搜索或跳转到…",
		"Type / to search": "输入 / 以搜索",
		"Open quick search dialog, type / to search":
			"打开快速搜索对话框，输入 / 进行搜索",
		"to search": "以进行搜索",
		"forward slash": "正斜杠",
		"g then n": "g 然后 n",
		"g then d": "g 然后 d",
		"Open menu": "打开菜单",
		"Open user navigation menu": "打开用户导航菜单",
		"You have no unread notifications": "你没有未读通知",
		"Switch repository": "切换仓库",
		"All repositories": "所有仓库",
		"All issues": "所有议题",
		"All pull requests": "所有拉取请求",
		"Chat with Copilot": "与 Copilot 聊天",
		"Open Copilot…": "打开 Copilot…",
		// —— 「+」新建菜单 ——
		New: "新建",
		"New repository": "新建仓库",
		"Import repository": "导入仓库",
		"New codespace": "新建代码空间",
		"New gist": "新建 Gist",
		"New organization": "新建组织",
		"New project": "新建项目",
		"New issue": "新建议题",
		"New pull request": "新建拉取请求",
		"Create new...": "新建…",
		// —— 用户菜单 ——
		"Your profile": "你的个人资料",
		"Your repositories": "你的仓库",
		"Your issues": "你的议题",
		"Your pull requests": "你的拉取请求",
		"Your stars": "你的星标",
		"Your gists": "你的 Gist",
		"Your organizations": "你的组织",
		"Signed in as": "当前登录身份",
		// —— 通用操作 ——
		Edit: "编辑",
		Delete: "删除",
		Save: "保存",
		Cancel: "取消",
		Close: "关闭",
		Confirm: "确认",
		Continue: "继续",
		Back: "返回",
		Done: "完成",
		More: "更多",
		Next: "下一页",
		Previous: "上一页",
		"Learn more": "了解更多",
		"Learn more about": "进一步了解",
		"Show more": "显示更多",
		"Show less": "收起",
		Copy: "复制",
		Download: "下载",
		Upload: "上传",
		Search: "搜索",
		Filter: "筛选",
		Sort: "排序",
		Clear: "清除",
		Preview: "预览",
		Write: "编写",
		Description: "描述",
		Details: "详情",
		Summary: "摘要",
		Overview: "概览",
		All: "全部",
		Language: "语言",
		Rename: "重命名",
		Restore: "恢复",
		Pin: "置顶",
		Unpin: "取消置顶",
		Subscribe: "订阅",
		Unsubscribe: "取消订阅",
		"Select all": "全选",
		// —— 状态徽标（议题 / PR / 工作流通用）——
		Open: "打开",
		Closed: "已关闭",
		Merged: "已合并",
		Draft: "草稿",
		Completed: "已完成",
		Success: "成功",
		Failure: "失败",
		Skipped: "已跳过",
		Cancelled: "已取消",
		"In progress": "进行中",
		Queued: "排队中",
		Pending: "等待中",
		// —— 人与关注 ——
		Author: "作者",
		Owner: "所有者",
		Assignees: "指派人",
		Reviewers: "审查者",
		Labels: "标签",
		Milestones: "里程碑",
		Milestone: "里程碑",
		Participants: "参与者",
		Follow: "关注",
		Unfollow: "取消关注",
		Followers: "关注者",
		Following: "正在关注",
		Sponsor: "赞助",
		Star: "星标",
		Unstar: "取消星标",
		Stars: "星标",
		Fork: "复刻",
		Forks: "复刻",
		Watch: "关注",
		Unwatch: "取消关注",
		Watching: "正在关注",
		Repositories: "仓库",
		Organizations: "组织",
		Pinned: "置顶",
		Achievements: "成就",
		// —— 页脚与法务 ——
		Terms: "条款",
		Privacy: "隐私",
		Docs: "文档",
		Status: "状态",
		Security: "安全",
		"Contact GitHub": "联系 GitHub",
		Contact: "联系方式",
		Community: "社区",
		"Manage cookies": "管理 Cookie",
		"Do not share my personal information":
			"不共享我的个人信息",
		// —— 导航区域标注（aria landmark 与面包屑）——
		Footer: "页脚",
		"Footer navigation": "页脚导航",
		"Repository navigation": "仓库导航",
		"Global navigation menu": "全局导航菜单",
		Breadcrumbs: "面包屑导航",
		"More items, including current item":
			"更多项目（包括当前项目）",
		Repository: "仓库",
		// —— 加载与错误提示（全站占位文案）——
		Loading: "加载中",
		"Loading...": "加载中…",
		"Loading content...": "正在加载内容…",
		"Uh oh!": "哎呀！",
		"There was an error while loading.": "加载时出现错误。",
		"Sorry, something went wrong.": "抱歉，出了点问题。",
		"Please reload this page": "请重新加载此页面",
		Reload: "重新加载",
		"to refresh your session.": "以刷新你的会话。",
		"You signed in with another tab or window.":
			"你在另一个标签页或窗口中登录了。",
		"You signed out in another tab or window.":
			"你在另一个标签页或窗口中退出了。",
		"You switched accounts on another tab or window.":
			"你在另一个标签页或窗口中切换了账户。",
		"Dismiss notice": "关闭通知",
		"Dismiss alert": "关闭提醒",
		"Dismiss error": "关闭错误",
		// —— 登录 / 注册页 ——
		"Sign in to GitHub": "登录 GitHub",
		"Username or email address": "用户名或电子邮箱",
		Password: "密码",
		"Forgot password?": "忘记密码？",
		"Create an account": "创建账户",
		"Remember me": "记住我",
	},
	rules: commonRules,
};
